<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SafeEcu.Application\SafeEcu.Application.csproj" />
    <ProjectReference Include="..\SafeEcu.Domain\SafeEcu.Domain.csproj" />
    <ProjectReference Include="..\SafeEcu.Infrastructure\SafeEcu.Infrastructure.csproj" />
    <ProjectReference Include="..\SafeEcu.Programmers\SafeEcu.Programmers.csproj" />
    <ProjectReference Include="..\SafeEcu.Calibration\SafeEcu.Calibration.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
