namespace SafeEcu.Application.Localization;

public sealed class InMemoryTextLocalizer : ITextLocalizer
{
    private const string English = "en";
    private const string Portuguese = "pt";

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Resources =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            [English] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["App.Title"] = "Safe ECU Calibration Manager",
                ["App.DatabaseWarningTitle"] = "Local database",
                ["App.UnhandledError"] = "An unexpected error occurred. The application logged details locally.",
                ["App.ErrorTitle"] = "Error",
                ["Language.Label"] = "Language",
                ["Status.AvailableNow"] = "Available in this phase",
                ["Status.FuturePhase"] = "Prepared for a future phase",
                ["Footer.SafeMode"] = "Safe mode: FileOnly / ManualWorkflow. ECU writing and direct hardware control are disabled.",
                ["Dashboard.Body"] = "Safe ECU Calibration Manager is currently at Phase 9: ECU/EDU identification.\n\nThe application has a desktop shell, main navigation, local logging, global error handling, SQLite persistence, vehicle records, ECU/EDU identification, safe programmer capability reporting, ECU file import, binary comparison and HTML report generation.\n\nDangerous capabilities remain disabled: ECU writing, flashing, direct Galletto 1260 control, real map modification and any technical bypass.",
                ["Section.FutureBody"] = "This section already exists in the navigation to stabilize the application structure, but its functionality will be implemented in its own phase.\n\nUntil validated support exists, the expected behavior is to block or mark the feature as NotSupported.",
                ["Nav.Dashboard.Title"] = "Dashboard",
                ["Nav.Dashboard.Description"] = "Application status and safe next steps.",
                ["Nav.Vehicles.Title"] = "Vehicles",
                ["Nav.Vehicles.Description"] = "Create, edit and review vehicle records.",
                ["Vehicles.Profile"] = "Profile",
                ["Vehicles.Profile.None"] = "No profile",
                ["Vehicles.New"] = "New",
                ["Vehicles.Save"] = "Save",
                ["Vehicles.Refresh"] = "Refresh",
                ["Vehicles.Make"] = "Make",
                ["Vehicles.Model"] = "Model",
                ["Vehicles.Year"] = "Year",
                ["Vehicles.Engine"] = "Engine",
                ["Vehicles.EngineCode"] = "Engine code",
                ["Vehicles.Fuel"] = "Fuel",
                ["Vehicles.Vin"] = "VIN",
                ["Vehicles.LicensePlate"] = "License plate",
                ["Vehicles.Notes"] = "Notes",
                ["Vehicles.ListTitle"] = "Registered vehicles",
                ["Vehicles.FormTitle.New"] = "New vehicle",
                ["Vehicles.FormTitle.Edit"] = "Vehicle details",
                ["Vehicles.Empty"] = "No vehicles registered yet.",
                ["Vehicles.SaveSuccess"] = "Vehicle saved.",
                ["Vehicles.SaveFailure"] = "Vehicle could not be saved.",
                ["Vehicles.InvalidYear"] = "Year must be empty or a valid number.",
                ["Vehicles.LoadFailure"] = "Vehicles could not be loaded.",
                ["Nav.Ecus.Title"] = "ECUs/EDUs",
                ["Nav.Ecus.Description"] = "Manual ECU/EDU identification with confidence and support status.",
                ["Ecus.Vehicle"] = "Vehicle",
                ["Ecus.ListTitle"] = "ECU/EDU records",
                ["Ecus.New"] = "New",
                ["Ecus.Save"] = "Save",
                ["Ecus.Refresh"] = "Refresh",
                ["Ecus.Manufacturer"] = "Manufacturer",
                ["Ecus.Family"] = "Family",
                ["Ecus.Hardware"] = "Hardware ref.",
                ["Ecus.Software"] = "Software ref.",
                ["Ecus.SoftwareVersion"] = "Software version",
                ["Ecus.Protocol"] = "Protocol",
                ["Ecus.SupportStatus"] = "Support status",
                ["Ecus.Notes"] = "Notes",
                ["Ecus.Confidence"] = "Identification confidence",
                ["Ecus.MissingEvidence"] = "Missing evidence",
                ["Ecus.SaveSuccess"] = "ECU/EDU saved.",
                ["Ecus.SaveFailure"] = "ECU/EDU could not be saved.",
                ["Ecus.NoVehicle"] = "Select a vehicle before saving ECU/EDU identification.",
                ["Ecus.LoadFailure"] = "ECU/EDU records could not be loaded.",
                ["Nav.EcuFiles.Title"] = "ECU Files",
                ["Nav.EcuFiles.Description"] = "Import externally read ECU files, calculate SHA-256 and store safe backups.",
                ["EcuFiles.Vehicle"] = "Vehicle",
                ["EcuFiles.FileType"] = "File type",
                ["EcuFiles.SourceFile"] = "Source file",
                ["EcuFiles.SelectFile"] = "Select file",
                ["EcuFiles.Import"] = "Import",
                ["EcuFiles.Refresh"] = "Refresh",
                ["EcuFiles.Origin"] = "File origin",
                ["EcuFiles.ReadMethod"] = "Read method",
                ["EcuFiles.Programmer"] = "Programmer used",
                ["EcuFiles.Notes"] = "Notes",
                ["EcuFiles.ImportedFiles"] = "Imported ECU files",
                ["EcuFiles.FileName"] = "File name",
                ["EcuFiles.Size"] = "Size",
                ["EcuFiles.Hash"] = "SHA-256",
                ["EcuFiles.Checksum"] = "Checksum",
                ["EcuFiles.ImportedAt"] = "Imported at",
                ["EcuFiles.NoVehicle"] = "Select a vehicle before importing an ECU file.",
                ["EcuFiles.NoFile"] = "Select an ECU file before importing.",
                ["EcuFiles.ImportSuccess"] = "ECU file imported and backed up.",
                ["EcuFiles.ImportFailure"] = "ECU file could not be imported.",
                ["EcuFiles.LoadFailure"] = "ECU files could not be loaded.",
                ["Nav.Programmers.Title"] = "Programmers",
                ["Nav.Programmers.Description"] = "FileOnly, Mock and Galletto 1260 manual workflow capabilities.",
                ["Programmers.ListTitle"] = "Available programmer adapters",
                ["Programmers.Name"] = "Name",
                ["Programmers.ConnectionType"] = "Connection",
                ["Programmers.Mode"] = "Mode",
                ["Programmers.DirectRead"] = "Direct read",
                ["Programmers.DirectWrite"] = "Direct write",
                ["Programmers.ExternalSoftware"] = "External software",
                ["Programmers.Notes"] = "Notes",
                ["Common.Yes"] = "Yes",
                ["Common.No"] = "No",
                ["Nav.Comparison.Title"] = "Comparison",
                ["Nav.Comparison.Description"] = "Compare imported Original and Modified ECU files without interpreting maps.",
                ["Comparison.Vehicle"] = "Vehicle",
                ["Comparison.OriginalFile"] = "Original file",
                ["Comparison.ModifiedFile"] = "Modified file",
                ["Comparison.Compare"] = "Compare",
                ["Comparison.Refresh"] = "Refresh",
                ["Comparison.Results"] = "Comparison results",
                ["Comparison.Differences"] = "Differences",
                ["Comparison.PercentChanged"] = "Changed",
                ["Comparison.Result"] = "Result",
                ["Comparison.ComparedAt"] = "Compared at",
                ["Comparison.NoVehicle"] = "Select a vehicle before comparing ECU files.",
                ["Comparison.NoOriginal"] = "Select an Original ECU file.",
                ["Comparison.NoModified"] = "Select a Modified ECU file.",
                ["Comparison.Success"] = "Binary comparison saved.",
                ["Comparison.Failure"] = "Binary comparison could not be completed.",
                ["Comparison.LoadFailure"] = "Comparison data could not be loaded.",
                ["Nav.Reports.Title"] = "Reports",
                ["Nav.Reports.Description"] = "Generate local HTML technical reports from saved comparisons.",
                ["Reports.Comparison"] = "Comparison",
                ["Reports.Generate"] = "Generate report",
                ["Reports.Refresh"] = "Refresh",
                ["Reports.Output"] = "Report output",
                ["Reports.NoComparison"] = "Select a comparison before generating a report.",
                ["Reports.Success"] = "Technical report generated.",
                ["Reports.Failure"] = "Technical report could not be generated.",
                ["Reports.LoadFailure"] = "Report data could not be loaded.",
                ["Nav.Audit.Title"] = "Audit",
                ["Nav.Audit.Description"] = "Auditable action history. Not implemented yet.",
                ["Nav.Settings.Title"] = "Settings",
                ["Nav.Settings.Description"] = "Local configuration and safety limits. Not implemented yet."
            },
            [Portuguese] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["App.Title"] = "Safe ECU Calibration Manager",
                ["App.DatabaseWarningTitle"] = "Base de dados local",
                ["App.UnhandledError"] = "Ocorreu um erro inesperado. A aplicacao registou detalhes no log local.",
                ["App.ErrorTitle"] = "Erro",
                ["Language.Label"] = "Idioma",
                ["Status.AvailableNow"] = "Disponivel nesta fase",
                ["Status.FuturePhase"] = "Preparado para fase futura",
                ["Footer.SafeMode"] = "Modo seguro: FileOnly / ManualWorkflow. Escrita ECU e controlo direto de hardware estao desativados.",
                ["Dashboard.Body"] = "Safe ECU Calibration Manager esta atualmente na Fase 9: identificacao ECU/EDU.\n\nA aplicacao ja tem shell desktop, navegacao principal, logging local, tratamento global de erros, persistencia SQLite, registos de veiculos, identificacao ECU/EDU, apresentacao segura de capacidades de programadores, importacao de ficheiros ECU, comparacao binaria e geracao de relatorios HTML.\n\nFuncionalidades perigosas permanecem desativadas: escrita ECU, flashing, controlo direto do Galletto 1260, alteracao real de mapas e qualquer bypass tecnico.",
                ["Section.FutureBody"] = "Esta seccao ja existe na navegacao para estabilizar a estrutura da aplicacao, mas a funcionalidade sera implementada numa fase propria.\n\nEnquanto nao existir suporte validado, o comportamento esperado e bloquear ou marcar como NotSupported.",
                ["Nav.Dashboard.Title"] = "Dashboard",
                ["Nav.Dashboard.Description"] = "Estado geral da aplicacao e proximos passos seguros.",
                ["Nav.Vehicles.Title"] = "Veiculos",
                ["Nav.Vehicles.Description"] = "Criar, editar e consultar registos de veiculos.",
                ["Vehicles.Profile"] = "Perfil",
                ["Vehicles.Profile.None"] = "Sem perfil",
                ["Vehicles.New"] = "Novo",
                ["Vehicles.Save"] = "Guardar",
                ["Vehicles.Refresh"] = "Atualizar",
                ["Vehicles.Make"] = "Marca",
                ["Vehicles.Model"] = "Modelo",
                ["Vehicles.Year"] = "Ano",
                ["Vehicles.Engine"] = "Motor",
                ["Vehicles.EngineCode"] = "Codigo motor",
                ["Vehicles.Fuel"] = "Combustivel",
                ["Vehicles.Vin"] = "VIN",
                ["Vehicles.LicensePlate"] = "Matricula",
                ["Vehicles.Notes"] = "Notas",
                ["Vehicles.ListTitle"] = "Veiculos registados",
                ["Vehicles.FormTitle.New"] = "Novo veiculo",
                ["Vehicles.FormTitle.Edit"] = "Detalhes do veiculo",
                ["Vehicles.Empty"] = "Ainda nao existem veiculos registados.",
                ["Vehicles.SaveSuccess"] = "Veiculo guardado.",
                ["Vehicles.SaveFailure"] = "Nao foi possivel guardar o veiculo.",
                ["Vehicles.InvalidYear"] = "O ano deve estar vazio ou conter um numero valido.",
                ["Vehicles.LoadFailure"] = "Nao foi possivel carregar os veiculos.",
                ["Nav.Ecus.Title"] = "ECUs/EDUs",
                ["Nav.Ecus.Description"] = "Identificacao manual ECU/EDU com confianca e estado de suporte.",
                ["Ecus.Vehicle"] = "Veiculo",
                ["Ecus.ListTitle"] = "Registos ECU/EDU",
                ["Ecus.New"] = "Novo",
                ["Ecus.Save"] = "Guardar",
                ["Ecus.Refresh"] = "Atualizar",
                ["Ecus.Manufacturer"] = "Fabricante",
                ["Ecus.Family"] = "Familia",
                ["Ecus.Hardware"] = "Ref. hardware",
                ["Ecus.Software"] = "Ref. software",
                ["Ecus.SoftwareVersion"] = "Versao software",
                ["Ecus.Protocol"] = "Protocolo",
                ["Ecus.SupportStatus"] = "Estado de suporte",
                ["Ecus.Notes"] = "Notas",
                ["Ecus.Confidence"] = "Confianca da identificacao",
                ["Ecus.MissingEvidence"] = "Evidencia em falta",
                ["Ecus.SaveSuccess"] = "ECU/EDU guardada.",
                ["Ecus.SaveFailure"] = "Nao foi possivel guardar a ECU/EDU.",
                ["Ecus.NoVehicle"] = "Seleciona um veiculo antes de guardar a identificacao ECU/EDU.",
                ["Ecus.LoadFailure"] = "Nao foi possivel carregar registos ECU/EDU.",
                ["Nav.EcuFiles.Title"] = "Ficheiros ECU",
                ["Nav.EcuFiles.Description"] = "Importar ficheiros ECU lidos externamente, calcular SHA-256 e guardar backups seguros.",
                ["EcuFiles.Vehicle"] = "Veiculo",
                ["EcuFiles.FileType"] = "Tipo de ficheiro",
                ["EcuFiles.SourceFile"] = "Ficheiro origem",
                ["EcuFiles.SelectFile"] = "Selecionar ficheiro",
                ["EcuFiles.Import"] = "Importar",
                ["EcuFiles.Refresh"] = "Atualizar",
                ["EcuFiles.Origin"] = "Origem do ficheiro",
                ["EcuFiles.ReadMethod"] = "Metodo de leitura",
                ["EcuFiles.Programmer"] = "Programador usado",
                ["EcuFiles.Notes"] = "Notas",
                ["EcuFiles.ImportedFiles"] = "Ficheiros ECU importados",
                ["EcuFiles.FileName"] = "Nome",
                ["EcuFiles.Size"] = "Tamanho",
                ["EcuFiles.Hash"] = "SHA-256",
                ["EcuFiles.Checksum"] = "Checksum",
                ["EcuFiles.ImportedAt"] = "Importado em",
                ["EcuFiles.NoVehicle"] = "Seleciona um veiculo antes de importar um ficheiro ECU.",
                ["EcuFiles.NoFile"] = "Seleciona um ficheiro ECU antes de importar.",
                ["EcuFiles.ImportSuccess"] = "Ficheiro ECU importado e guardado em backup.",
                ["EcuFiles.ImportFailure"] = "Nao foi possivel importar o ficheiro ECU.",
                ["EcuFiles.LoadFailure"] = "Nao foi possivel carregar os ficheiros ECU.",
                ["Nav.Programmers.Title"] = "Programadores",
                ["Nav.Programmers.Description"] = "Capacidades dos fluxos FileOnly, Mock e Galletto 1260 manual.",
                ["Programmers.ListTitle"] = "Adapters de programador disponiveis",
                ["Programmers.Name"] = "Nome",
                ["Programmers.ConnectionType"] = "Ligacao",
                ["Programmers.Mode"] = "Modo",
                ["Programmers.DirectRead"] = "Leitura direta",
                ["Programmers.DirectWrite"] = "Escrita direta",
                ["Programmers.ExternalSoftware"] = "Software externo",
                ["Programmers.Notes"] = "Notas",
                ["Common.Yes"] = "Sim",
                ["Common.No"] = "Nao",
                ["Nav.Comparison.Title"] = "Comparacao",
                ["Nav.Comparison.Description"] = "Comparar ficheiros ECU importados Original e Modified sem interpretar mapas.",
                ["Comparison.Vehicle"] = "Veiculo",
                ["Comparison.OriginalFile"] = "Ficheiro original",
                ["Comparison.ModifiedFile"] = "Ficheiro modificado",
                ["Comparison.Compare"] = "Comparar",
                ["Comparison.Refresh"] = "Atualizar",
                ["Comparison.Results"] = "Resultados da comparacao",
                ["Comparison.Differences"] = "Diferencas",
                ["Comparison.PercentChanged"] = "Alterado",
                ["Comparison.Result"] = "Resultado",
                ["Comparison.ComparedAt"] = "Comparado em",
                ["Comparison.NoVehicle"] = "Seleciona um veiculo antes de comparar ficheiros ECU.",
                ["Comparison.NoOriginal"] = "Seleciona um ficheiro ECU Original.",
                ["Comparison.NoModified"] = "Seleciona um ficheiro ECU Modified.",
                ["Comparison.Success"] = "Comparacao binaria guardada.",
                ["Comparison.Failure"] = "Nao foi possivel concluir a comparacao binaria.",
                ["Comparison.LoadFailure"] = "Nao foi possivel carregar dados de comparacao.",
                ["Nav.Reports.Title"] = "Relatorios",
                ["Nav.Reports.Description"] = "Gerar relatorios tecnicos HTML locais a partir de comparacoes guardadas.",
                ["Reports.Comparison"] = "Comparacao",
                ["Reports.Generate"] = "Gerar relatorio",
                ["Reports.Refresh"] = "Atualizar",
                ["Reports.Output"] = "Saida do relatorio",
                ["Reports.NoComparison"] = "Seleciona uma comparacao antes de gerar um relatorio.",
                ["Reports.Success"] = "Relatorio tecnico gerado.",
                ["Reports.Failure"] = "Nao foi possivel gerar o relatorio tecnico.",
                ["Reports.LoadFailure"] = "Nao foi possivel carregar os dados de relatorio.",
                ["Nav.Audit.Title"] = "Auditoria",
                ["Nav.Audit.Description"] = "Historico auditavel de acoes. Ainda nao implementado.",
                ["Nav.Settings.Title"] = "Definicoes",
                ["Nav.Settings.Description"] = "Configuracao local e limites de seguranca. Ainda nao implementado."
            }
        };

    private string _currentLanguageCode;

    public InMemoryTextLocalizer(string defaultLanguageCode = English)
    {
        _currentLanguageCode = Resources.ContainsKey(defaultLanguageCode) ? defaultLanguageCode : English;
    }

    public string CurrentLanguageCode => _currentLanguageCode;

    public IReadOnlyList<LanguageOption> SupportedLanguages { get; } =
    [
        new(English, "English"),
        new(Portuguese, "Portuguese")
    ];

    public void SetLanguage(string languageCode)
    {
        _currentLanguageCode = Resources.ContainsKey(languageCode) ? languageCode : English;
    }

    public string Text(string key)
    {
        if (Resources[_currentLanguageCode].TryGetValue(key, out var localizedText))
        {
            return localizedText;
        }

        return Resources[English].TryGetValue(key, out var fallbackText) ? fallbackText : key;
    }
}
